name: Terraform Validate

on:
  pull_request:
    paths:
      - '**.tf'
  push:
    branches: [main]
    paths:
      - '**.tf'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate
